# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- sbvconnect

pool:
  vmImage: ubuntu-latest


stages:
  - stage: CheckoutCode
    jobs:
      - job: "Checkoutgitcode"
        steps:
          - checkout: self
  - stage: 'Build'
    jobs:
      - job:
        steps:      
          - task: Maven@3
            inputs:
             mavenPomFile: 'pom.xml'
             goals: 'install'
             mavenOptions: '-Xmx3072m'
             javaHomeOption: 'JDKVersion'
             jdkVersionOption: '1.8'
             jdkArchitectureOption: 'x64'
             publishJUnitResults: true
             testResultsFiles: '**/surefire-reports/TEST-*.xml'
             
